intro = `<p class="c-gray">Piezas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.</p><br>`

cuidados = `
    <h4>Cuidados y Recomendaciones:</h4>
    <ul class='list'>
        <li>Evita el contacto con productos químicos o de aseo en general.</li>
        <li>Las cremas, el perfume y el agua pueden alterar su color original.</li>
        <li>Evita golpear tu joya.</li>
        <li>No la uses para bañarte en piscinas o en el mar. </li>
        <li>Guárdala por separado para evitar desgaste o enredos por roce con otros accesorios.</li>
    </ul>
    <br>
    <h4 style='text-align: center;'><i><b>Realizamos envíos nacionales.</b></i></h4>
`

categories = [
    {"id": 1, "name": "Set de pulseras"},
    {"id": 2, "name": "Set de Collar y Aretes"},
    {"id": 3, "name": "Pulsera Dama"},
    {"id": 4, "name": "Pulsera Caballero"},
    {"id": 5, "name": "Aretes"},
    {"id": 6, "name": "Aretes Simbólicos"},
    {"id": 7, "name": "Tobillera"},
    {"id": 8, "name": "Collar / Choker"},
    {"id": 9, "name": "Dije"},
    {"id": 10, "name": "Anillo"},
    {"id": 11, "name": "Set de Anillos"},
    {"id": 12, "name": "Religioso"},
    {"id": 13, "name": "Portagafas"},
    {"id": 14, "name": "Caja de regalo"},
    {"id": 15, "name": "Complemento"},
]

catalog = [   

    {"id": "001", 
    "title": "JOYAS CON PIEZAS DE ORO 18 KILATES", 
    "category": 1, 
    "price" : "$51.000", 
    "image": ["001-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br> <b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°3mm."},

    {"id": "002", 
    "title": "ANILLO", 
    "category": "10", 
    "price" : "$35.000", 
    "image": ["002-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br> <b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "003", 
    "title": "COLLAR CHOKER", 
    "category": 8, 
    "price" : "$25.000", 
    "image": ["003-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado.<br>Medida aproximada de choker entre 38 a 40 cm con extensión de cadena."}, 

    {"id": "004", 
    "title": "JOYAS PARA COMPARTIR", 
    "category": 3, 
    "price" : "$90.000", 
    "image": ["004-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "005", 
    "title": "RELIGIOSO", 
    "category": 7, 
    "price" : "$20.000", 
    "image": ["005-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "006", 
    "title": "PULSERA", 
    "category": 3, 
    "price" : "$60.000", 
    "image": ["006-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "007", 
    "title": "CABALLERO: JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 4, 
    "price" : "$56.000", 
    "image": ["007-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>2 balines de oro 18 quilates N°3mm."},     

    {"id": "008", 
    "title": "ARETES TOPOS GEOMÉTRICOS: Forma triangular", 
    "category": 5, 
    "price" : "$40.000", 
    "image": ["008-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "009", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 3, 
    "price" : "$38.000", 
    "image": ["009-01.jpg", "009-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>1 balin de oro 18 quilates N°3mm."}, 

    {"id": "010", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$28.000", 
    "image": ["010-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Perla natural."}, 

    {"id": "011", 
    "title": "CAJA DE REGALO", 
    "category": 14, 
    "price" : "$64.000", 
    "image": ["011-01.jpg"],
    "description": "Caja de regalo con joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.<br><br>Complementamos con otros productos de marcas Sucreñas o Nacionales para que el detalle tenga un toque más especial.<br><br>1. Set de collar y aretes con aplique de cristal chapado de oro y cadena de acero: $40.000.<br>2. Vinotinto Gato Negro 187 ml: $18.000.<br>3. Chocolate Moments: $6.000.<br>Se obsequia la caja decorativa que incluye: lazo en tela, tarjeta escrita en máquina, aplique floral seco."}, 

    {"id": "012", 
    "title": "CAJA DE REGALO", 
    "category": 14, 
    "price" : "$29.000", 
    "image": ["012-01.jpg", "012-02.jpg"],
    "description": "Complementamos con otros productos de marcas Sucreñas o Nacionales para que el detalle tenga un toque más especial.<br><br>Contiene:<br>1. Pulsera tejida a mano: $20.000<br>2. Scrunch talla M de la marca Diana Designs: $9.000<br>Se obsequia la caja decorativa (incluye aplique floral, tarjeta escrita a máquina, cinta)."}, 

    {"id": "013", 
    "title": "CAJA DE REGALO", 
    "category": 14, 
    "price" : "$58.000", 
    "image": ["013-01.jpg"],
    "description": "Complementamos con otros productos de marcas Sucreñas o Nacionales para que el detalle tenga un toque más especial.<br><br>Set de pulseras tejidas a mano: $38.000<br><br>Te Hatsu 250ml: $5.000<br>Galletas artesanales de la marca Cookieland por 2 unidades: $15.000<br>Se obsequia la caja decorativa (incluye aplique floral, tarjeta escrita a máquina, cinta de tela)."}, 

    {"id": "014", 
    "title": "TOBILLERA", 
    "category": 7, 
    "price" : "$23.000", 
    "image": ["014-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado"}, 

    {"id": "015", 
    "title": "JP CHENET", 
    "category": 15, 
    "price" : "$13.000", 
    "image": ["015-01.jpg"],
    "description": "Este producto es una opción para complementar las joyas tejidas a mano y de esta forma organizar cajas de regalo especiales para obsequiar. <br><br>Marca: JP Chenet France<br>Presentación: 1 lata 250 ml"}, 

    {"id": "016", 
    "title": "VINO ESPUMOSO JAUME SERRA", 
    "category": 15, 
    "price" : "$18.000", 
    "image": ["016-01.jpg"],
    "description": "Este producto es una opción para complementar las joyas tejidas a mano y de esta forma organizar cajas de regalo especiales para obsequiar. <br><br>Marca: Brut Nature.<br>Presentación: 1 botella 200ml."}, 

    {"id": "017", 
    "title": "CABALLERO: JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 4, 
    "price" : "$80.000", 
    "image": ["017-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>2 balines de oro 18 quilates N°4mm."}, 

    {"id": "018", 
    "title": "JOYAS PARA COMPARTIR", 
    "category": 1, 
    "price" : "$76.000", 
    "image": ["018-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado. <br>2 balines de oro 18 quilates N°3mm."}, 

    {"id": "019", 
    "title": "CABALLERO: JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 4, 
    "price" : "$105.000", 
    "image": ["019-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilo encerado. <br><2 balines de oro 18 quilates N°4mm."}, 

    {"id": "020", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 3, 
    "price" : "$50.000", 
    "image": ["020-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°3mm."}, 

    {"id": "021", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 3, 
    "price" : "$38.000", 
    "image": ["021-01.jpg", "021-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilo con brillo.<br>1 balin de oro 18 quilates N3mm.<br>Hilo encerado."}, 

    {"id": "022", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 3, 
    "price" : "$50.000", 
    "image": ["022-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."}, 

    {"id": "023", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 3, 
    "price" : "$68.000", 
    "image": ["023-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°5mm."}, 

    {"id": "024", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 3, 
    "price" : "$50.000", 
    "image": ["024-01.jpg", "024-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."}, 
    
    {"id": "025", 
    "title": "JOYAS PARA COMPARTIR", 
    "category": 1, 
    "price" : "$100.000", 
    "image": ["018-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado. <br>2 balines de oro 18 quilates N°4mm."}, 

    {"id": "026", 
    "title": "CABALLERO: JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 4, 
    "price" : "$63.000", 
    "image": ["026-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>1 balin de oro 18 quilates N4mm.<br>Hilo encerado"}, 

    {"id": "027", 
    "title": "JOYAS CON PIEZAS DE ORO", 
    "category": 1, 
    "price" : "$78.000", 
    "image": ["027-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."}, 

    {"id": "028", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$123.000", 
    "image": ["028-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>5 balines de oro 18 quilates N°3mm."}, 

    {"id": "029", 
    "title": "CABALLERO: JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 4, 
    "price" : "$75.000", 
    "image": ["029-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."},

    {"id": "030", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$118.000", 
    "image": ["030-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>4 balines de oro 18 quilates N°3mm."}, 

    {"id": "031", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$86.000", 
    "image": ["031-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."}, 

    {"id": "032", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$128.000", 
    "image": ["032-01.jpg", "032-02.jpg", "032-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>5 balines de oro 18 quilates N°3mm."}, 
    
    {"id": "033", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$136.000", 
    "image": ["033-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>3 balines de oro 18 quilates N°4mm."}, 

    {"id": "034", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$38.000", 
    "image": ["034-01.jpg", "034-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Piedra natural."}, 

    {"id": "035", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$151.000", 
    "image": ["035-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>3 balines de oro 18 quilates N°4mm."}, 

    {"id": "036", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$110.000", 
    "image": ["036-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>3 balines de oro 18 quilates N°3mm."}, 

    {"id": "037", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$105.000", 
    "image": ["037-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>3 balines de oro 18 quilates N°3mm."}, 

    {"id": "038", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$71.000", 
    "image": ["038-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro.<br>Piedra natural rodonita."}, 

    {"id": "039", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$56.000", 
    "image": ["039-01.jpg", "039-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro."}, 

    {"id": "040", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$74.000", 
    "image": ["040-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro."}, 

    {"id": "041", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$51.000", 
    "image": ["041-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro."}, 

    {"id": "042", 
    "title": "CAJA DE REGALO", 
    "category": 14, 
    "price" : "$115.000", 
    "image": ["042-01.jpg"],
    "description": "Complementamos con otros productos de marcas Sucreñas o Nacionales para que el detalle tenga un toque más especial.<br><br>Set de pulseras tejidas a mano: $66.000<br>Chocolate Moments: $6.000<br>Aretes tejidos a mano: $30.000<br>Bebida JP Chenet: $13.000<br><br>Se obsequia caja decorativa (incluye aplique floral, tarjeta escrita a máquina, cinta de tela)."}, 

    {"id": "043", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$61.000", 
    "image": ["043-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro."}, 

    {"id": "044", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$192.000", 
    "image": ["044-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo con brillo.<br>2 balin de oro 18 quilates N4mm.<br>2 balin de oro 18 quilates N3mm.<br><1 balin de oro 18 quilates diamantado N3mm.<br>Hilo encerado. <br>Piedras naturales rodonita: Se utiliza para equilibrar y asentar la energía."}, 

    {"id": "045", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$56.000", 
    "image": ["045-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Centro de pulsera con cristal y Goldfilled chapado de oro."}, 

    {"id": "046", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$48.000", 
    "image": ["046-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro."}, 

    {"id": "047", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$51.000", 
    "image": ["047-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro.<br>Cristales de Swarovski."}, 

    {"id": "048", 
    "title": "DIJE VIRGEN", 
    "category": 9, 
    "price" : "$40.000", 
    "image": ["048-01.jpg"],
    "description": "Se elaboran las advocaciones de la Virgen. Para este caso: Virgen Rosa Mística.<br><br><b>Materiales:</b>Mostacilla japonesa.<br>Cadena de acero dorado. Medida aproximada 40 cm."}, 

    {"id": "049", 
    "title": "CHOKER", 
    "category": 8, 
    "price" : "$30.000", 
    "image": ["049-01.jpg"],
    "description": "Sistema de cierre con broche y extensión de cadena para graduar a tu cuello.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Herrajes de acero dorado."}, 

    {"id": "050", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 3, 
    "price" : "$61.000", 
    "image": ["050-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>2 balines de oro 18 quilates N°3mm."}, 

    {"id": "051", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$40.000", 
    "image": ["051-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°3mm."}, 

    {"id": "052", 
    "title": "CABALLEROS: JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 4, 
    "price" : "$50.000", 
    "image": ["052-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."}, 

    {"id": "053", 
    "title": "PULSERA", 
    "category": 3, 
    "price" : "$65.000", 
    "image": ["053-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "054", 
    "title": "RELIGIOSO ESCAPULARIO", 
    "category": 1, 
    "price" : "$35.000", 
    "image": ["054-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "055", 
    "title": "PULSERA", 
    "category": 3, 
    "price" : "$15.000", 
    "image": ["055-01.jpg", "055-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano <br>Perla Shell."}, 

    {"id": "056", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$93.000", 
    "image": ["056-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>2 balines de oro diamantados 18 quilates N°3mm."}, 

    {"id": "057", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$51.000", 
    "image": ["057-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "058", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$46.000", 
    "image": ["058-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Aplique de cristal de Swarovski."}, 

    {"id": "059", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$61.000", 
    "image": ["059-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Centro de pulsera de acero."}, 

    {"id": "060", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$56.000", 
    "image": ["060-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Centro de pulsera de acero.<br>"}, 

    {"id": "061", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$120.000", 
    "image": ["061-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "062", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$66.000", 
    "image": ["062-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Aplique de cristal con gold filled con chapado de oro."}, 

    {"id": "063", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$71.000", 
    "image": ["063-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Aplique de cristal con gold filled con chapado de oro."}, 

    {"id": "064", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$61.000", 
    "image": ["064-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Aplique de cristal con gold filled con chapado de oro."}, 

    {"id": "065", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$61.000", 
    "image": ["065-01.jpg", "065-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Balines de gold filled con chapado de oro. <br>Piedra natural Turquesa Africana: Promueve la aceptación y alivia los sentimientos de dolor emocional resultando en una actitud más optimista hacia la vida."}, 

    {"id": "066", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$76.000", 
    "image": ["066-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro.<br>Piedra natural Turquesa Africana: Promueve la aceptación y alivia los sentimientos de dolor emocional resultando en una actitud más optimista hacia la vida."}, 

    {"id": "067", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$66.000", 
    "image": ["067-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Balines de gold filled con chapado de oro. <br>Piedra natural rodonita."}, 
    
    {"id": "068", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$61.000", 
    "image": ["068-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro.<br>Piedras Ágatas."}, 

    {"id": "069", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$51.000", 
    "image": ["069-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Balines de gold filled con chapado de oro."}, 

    {"id": "070", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$33.000", 
    "image": ["070-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Aplique de golfilled con chapado de oro."}, 

    {"id": "071", 
    "title": "", 
    "category": 8, 
    "price" : "$35.000", 
    "image": ["071-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Herrajes en golfilled con chapado de oro."}, 

    {"id": "072", 
    "title": "PULSERA ESCAPULARIO", 
    "category": 3, 
    "price" : "$30.000", 
    "image": ["072-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Balines de gold filled con chapado de oro.<br>"}, 

    {"id": "073", 
    "title": "TOBILLERA ESCAPULARIO", 
    "category": 7, 
    "price" : "$30.000", 
    "image": ["073-01.jpg", "073-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo chino"},

    {"id": "074", 
    "title": "PULSERA ESCAPULARIO", 
    "category": 3, 
    "price" : "$35.000", 
    "image": ["074-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo chino.<br>Balines de gold filled con chapado de oro."}, 

    {"id": "075", 
    "title": "COLLAR CHOKER ESCAPULARIO", 
    "category": 8, 
    "price" : "$45.000", 
    "image": ["075-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Herrajes en golfilled con chapado de oro."}, 

    {"id": "076", 
    "title": "RELIGIOSO: PULSERA", 
    "category": 3, 
    "price" : "$25.000", 
    "image": ["076-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "077", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$60.000", 
    "image": ["077-01.jpg", "077-02.jpg", "077-03.jpg", "077-04.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado.<br>1 balines de oro 18 quilates N°3mm."}, 

    {"id": "078", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$55.000", 
    "image": ["078-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo con brillo.<br>1 balin de oro 18 quilates N3mm.<br>Hilo encerado."}, 
    
    {"id": "079", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$75.000", 
    "image": ["079-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°3mm."}, 

    {"id": "080", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$80.000", 
    "image": ["080-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."}, 

    {"id": "081", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$92.000", 
    "image": ["081-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>2 balines de oro 18 quilates N°3mm."}, 

    {"id": "082", 
    "title": "CABALLERO", 
    "category": 4, 
    "price" : "$37.000", 
    "image": ["082-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "083", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$75.000", 
    "image": ["083-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°3mm."}, 

    {"id": "084", 
    "title": "SET DE PULSERAS", 
    "category": 1, 
    "price" : "$28.000", 
    "image": ["084-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "085", 
    "title": "CABALLERO", 
    "category": 4, 
    "price" : "$60.000", 
    "image": ["085-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Cuero natural."}, 

    {"id": "086", 
    "title": "PULSERA", 
    "category": 3, 
    "price" : "$25.000", 
    "image": ["086-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Aplique de cristal Goldfilled con chapado de oro."}, 

    {"id": "087", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$94.000", 
    "image": ["087-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro.<br>Piedra natural Lapizazuli: Sus propiedades van desde desprender el estrés y aportar calma, hasta la armonización mental, emocional y física."}, 

    {"id": "088", 
    "title": "PULSERA", 
    "category": 3, 
    "price" : "$30.000", 
    "image": ["088-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "089", 
    "title": "PULSERA", 
    "category": 3, 
    "price" : "$50.000", 
    "image": ["089-01.jpg", "089-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "090", 
    "title": "PULSERA CABALLERO", 
    "category": 4, 
    "price" : "$32.000", 
    "image": ["090-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "091", 
    "title": "PULSERA CABALLERO", 
    "category": 4, 
    "price" : "$27.000", 
    "image": ["091-01.jpg", "091-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "092", 
    "title": "PULSERA CABALLERO",
    "category": 4, 
    "price" : "$17.000", 
    "image": ["092-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "093", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$48.000", 
    "image": ["093-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Balines de gold filled con chapado de oro."}, 

    {"id": "094", 
    "title": "JOYAS CON PIEZAS DE GOLD FILLED CHAPADO DE ORO", 
    "category": 1, 
    "price" : "$63.000", 
    "image": ["094-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Centro de pulsera de gold filled con chapado de oro."}, 

    {"id": "095", 
    "title": "ARETES HEXAGONALES: DESDE LA MONTAÑA", 
    "category": 6, 
    "price" : "$70.000", 
    "image": ["095-01.jpg"],
    "description": "Inspirados en la Serranía de Coraza, Colosó-Sucre.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Topos de acero dorado."}, 

    {"id": "096", 
    "title": "ARETES HEXAGONALES", 
    "category": 5, 
    "price" : "$80.000", 
    "image": ["096-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Topos de acero dorado."}, 

    {"id": "097", 
    "title": "ARETES SIMBÓLICOS: PACHAMAMA", 
    "category": 6, 
    "price" : "$100.000", 
    "image": ["097-01.jpg"],
    "description": "Inspirados en la fertilidad de nuestro suelo Sucreño que hacen florecer a hermosas plantas.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Topos de acero dorado."}, 

    {"id": "098", 
    "title": "ARETES TOPOS GEOMÉTRICOS TRIANGULARES", 
    "category": 5, 
    "price" : "$50.000", 
    "image": ["098-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "099", 
    "title": "PULSERA", 
    "category": 3, 
    "price" : "$30.000", 
    "image": ["099-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Aplique de cristal Goldfilled con chapado de oro."}, 

    {"id": "100", 
    "title": "JOYAS CON PIEZAS DE ORO 18 QUILATES", 
    "category": 1, 
    "price" : "$80.000", 
    "image": ["100-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>1 balin de oro 18 quilates N°4mm."}, 
]

/*

    {"id": "", 
    "title": "", 
    "category": , 
    "price" : "$", 
    "image": [".jpg"],
    "description": ""}, 

*/

